services:
  oms-backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update  # LOCK THIS HERE
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ep-dark-sky-akqm6a17-pooler.c-3.us-west-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - JWT_KEY=your_secret_key
    restart: always